# Spark Defaults Configuration File
# This file stores shared configurations for all Spark applications running in this project.
# It is mounted to /opt/spark/conf/spark-defaults.conf in all Spark containers.

# Extensions and Catalog
spark.sql.extensions                      org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.stock_catalog           org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.stock_catalog.type      rest
spark.sql.catalog.stock_catalog.uri       http://iceberg-catalog:8181
spark.sql.catalog.stock_catalog.io-impl   org.apache.iceberg.hadoop.HadoopFileIO
spark.sql.catalog.stock_catalog.warehouse  s3a://stock-datalake

# MinIO / S3 Connection (s3a schema)
spark.hadoop.fs.s3a.endpoint              http://minio:9000
spark.hadoop.fs.s3a.access.key            minioadmin
spark.hadoop.fs.s3a.secret.key            minioadmin
spark.hadoop.fs.s3a.path.style.access     true
spark.hadoop.fs.s3a.impl                  org.apache.hadoop.fs.s3a.S3AFileSystem

# MinIO / S3 Connection (s3 schema)
spark.hadoop.fs.s3.endpoint               http://minio:9000
spark.hadoop.fs.s3.access.key             minioadmin
spark.hadoop.fs.s3.secret.key             minioadmin
spark.hadoop.fs.s3.path.style.access      true
spark.hadoop.fs.s3.impl                   org.apache.hadoop.fs.s3a.S3AFileSystem

# Shared Jars and Packages
spark.jars.packages                       org.apache.iceberg:iceberg-spark-runtime-3.5_2.12:1.5.0,org.apache.hadoop:hadoop-aws:3.3.4
