CREATE DATABASE IF NOT EXISTS stock_db;

-- 1. Target ClickHouse Native Table
CREATE TABLE IF NOT EXISTS stock_db.realtime_quotes_ch (
    ticker String,
    prd_id DateTime64(3, 'UTC'),
    last_price Nullable(Decimal(18, 4)),
    avg_price Nullable(Decimal(18, 4)),
    last_volume Nullable(Int64),
    total_volume Nullable(Int64),
    total_value Nullable(Decimal(18, 4)),
    foreign_buy_qty Nullable(Int64),
    foreign_sell_qty Nullable(Int64),
    foreign_buy_val Nullable(Decimal(18, 4)),
    foreign_sell_val Nullable(Decimal(18, 4)),
    bid1_price Nullable(Decimal(18, 4)),
    bid1_qty Nullable(Int64),
    bid2_price Nullable(Decimal(18, 4)),
    bid2_qty Nullable(Int64),
    bid3_price Nullable(Decimal(18, 4)),
    bid3_qty Nullable(Int64),
    ask1_price Nullable(Decimal(18, 4)),
    ask1_qty Nullable(Int64),
    ask2_price Nullable(Decimal(18, 4)),
    ask2_qty Nullable(Int64),
    ask3_price Nullable(Decimal(18, 4)),
    ask3_qty Nullable(Int64),
    ref_price Nullable(Decimal(18, 4)),
    ceil_price Nullable(Decimal(18, 4)),
    floor_price Nullable(Decimal(18, 4)),
    change_percent Nullable(Decimal(18, 4)),
    change_value Nullable(Decimal(18, 4)),
    high_price Nullable(Decimal(18, 4)),
    low_price Nullable(Decimal(18, 4)),
    import_time DateTime64(6, 'UTC') DEFAULT now64(6, 'UTC')
) ENGINE = MergeTree()
ORDER BY (ticker, prd_id);

-- 2. Kafka Engine Consumer Table (Flat Schema with Float64 for numeric columns to handle decimal values in JSON)
CREATE TABLE IF NOT EXISTS stock_db.kafka_realtime_quotes_ch (
    symbol String,
    ts Nullable(Float64),
    last_price Nullable(Decimal(18, 4)),
    avg_price Nullable(Decimal(18, 4)),
    last_volume Nullable(Float64),
    total_volume Nullable(Float64),
    total_value Nullable(Decimal(18, 4)),
    foreign_buy_qty Nullable(Float64),
    foreign_sell_qty Nullable(Float64),
    foreign_buy_val Nullable(Decimal(18, 4)),
    foreign_sell_val Nullable(Decimal(18, 4)),
    bid1_price Nullable(Decimal(18, 4)),
    bid1_qty Nullable(Float64),
    bid2_price Nullable(Decimal(18, 4)),
    bid2_qty Nullable(Float64),
    bid3_price Nullable(Decimal(18, 4)),
    bid3_qty Nullable(Float64),
    ask1_price Nullable(Decimal(18, 4)),
    ask1_qty Nullable(Float64),
    ask2_price Nullable(Decimal(18, 4)),
    ask2_qty Nullable(Float64),
    ask3_price Nullable(Decimal(18, 4)),
    ask3_qty Nullable(Float64),
    ref_price Nullable(Decimal(18, 4)),
    ceil_price Nullable(Decimal(18, 4)),
    floor_price Nullable(Decimal(18, 4)),
    change_percent Nullable(Decimal(18, 4)),
    change_value Nullable(Decimal(18, 4)),
    high_price Nullable(Decimal(18, 4)),
    low_price Nullable(Decimal(18, 4))
) ENGINE = Kafka
SETTINGS kafka_broker_list = 'kafka:9093',
         kafka_topic_list = 'market.quotes.raw',
         kafka_group_name = 'clickhouse-realtime-group-v4',
         kafka_format = 'JSONEachRow';

-- 3. Materialized View to sync Kafka messages to Target Table
CREATE MATERIALIZED VIEW IF NOT EXISTS stock_db.mv_kafka_to_realtime_quotes_ch TO stock_db.realtime_quotes_ch AS
SELECT
    symbol AS ticker,
    toDateTime64(CAST(ts, 'Nullable(Int64)') / 1000, 3, 'UTC') AS prd_id,
    last_price,
    avg_price,
    CAST(last_volume, 'Nullable(Int64)') AS last_volume,
    CAST(total_volume, 'Nullable(Int64)') AS total_volume,
    total_value,
    CAST(foreign_buy_qty, 'Nullable(Int64)') AS foreign_buy_qty,
    CAST(foreign_sell_qty, 'Nullable(Int64)') AS foreign_sell_qty,
    foreign_buy_val,
    foreign_sell_val,
    bid1_price,
    CAST(bid1_qty, 'Nullable(Int64)') AS bid1_qty,
    bid2_price,
    CAST(bid2_qty, 'Nullable(Int64)') AS bid2_qty,
    bid3_price,
    CAST(bid3_qty, 'Nullable(Int64)') AS bid3_qty,
    ask1_price,
    CAST(ask1_qty, 'Nullable(Int64)') AS ask1_qty,
    ask2_price,
    CAST(ask2_qty, 'Nullable(Int64)') AS ask2_qty,
    ask3_price,
    CAST(ask3_qty, 'Nullable(Int64)') AS ask3_qty,
    ref_price,
    ceil_price,
    floor_price,
    change_percent,
    change_value,
    high_price,
    low_price,
    now64(6, 'UTC') AS import_time
FROM stock_db.kafka_realtime_quotes_ch;
