// ==================== INDICES DATA ====================

export interface MarketIndex {
    name: string;
    asset_type?: string;
    flag: string; // emoji flag
    sparkline: number[]; // 30-day mini chart data
    history?: { date: string; close: number }[];
    value: number;
    change: number;
    changePercent: number;
    week1: number;
    ytd: number;
    year1: number;
    year3: number;
}

export interface MacroIndicator {
    name: string;
    category: string;
    value: string;
    change: number;
    changePercent: number;
    unit: string;
    period: string;
    previousValue: string;
    trend: "up" | "down" | "stable";
}

// Sparkline generators
function generateSparkline(base: number, volatility: number, trend: number): number[] {
    const data: number[] = [];
    let v = base;
    for (let i = 0; i < 30; i++) {
        v += (Math.random() - 0.48) * volatility + trend;
        data.push(Math.round(v * 100) / 100);
    }
    return data;
}

export const VIETNAM_MARKET_INDICES: MarketIndex[] = [
    {
        name: "VNINDEX",
        flag: "🇻🇳",
        sparkline: generateSparkline(1800, 8, 0.3),
        value: 1824.09,
        change: 10.00,
        changePercent: 0.55,
        week1: 3.91,
        ytd: 2.22,
        year1: 43.59,
        year3: 75.62,
    },
    {
        name: "HNXINDEX",
        flag: "🇻🇳",
        sparkline: generateSparkline(255, 2, -0.05),
        value: 257.06,
        change: -0.57,
        changePercent: 0.23,
        week1: 0.30,
        ytd: 3.33,
        year1: 12.00,
        year3: 25.48,
    },
    {
        name: "UPCOM",
        flag: "🇻🇳",
        sparkline: generateSparkline(125, 1.5, 0.1),
        value: 127.34,
        change: 1.40,
        changePercent: 1.11,
        week1: 1.46,
        ytd: 5.27,
        year1: 30.28,
        year3: 63.38,
    },
    {
        name: "VN30",
        flag: "🇻🇳",
        sparkline: generateSparkline(2010, 10, -0.2),
        value: 2018.64,
        change: 2.17,
        changePercent: 0.11,
        week1: 3.86,
        ytd: -0.59,
        year1: 50.89,
        year3: 95.05,
    },
    {
        name: "HNX30",
        flag: "🇻🇳",
        sparkline: generateSparkline(560, 3, 0.15),
        value: 563.37,
        change: 2.65,
        changePercent: 0.47,
        week1: 1.09,
        ytd: 4.69,
        year1: 19.39,
        year3: 62.22,
    },
    {
        name: "VNMID",
        flag: "🇻🇳",
        sparkline: generateSparkline(1420, 7, 0.2),
        value: 1435.12,
        change: 5.32,
        changePercent: 0.37,
        week1: 2.15,
        ytd: 3.89,
        year1: 38.45,
        year3: 68.90,
    },
    {
        name: "VNSML",
        flag: "🇻🇳",
        sparkline: generateSparkline(1180, 6, 0.1),
        value: 1192.45,
        change: -3.21,
        changePercent: -0.27,
        week1: 1.82,
        ytd: 6.14,
        year1: 25.67,
        year3: 52.34,
    },
    {
        name: "VN100",
        flag: "🇻🇳",
        sparkline: generateSparkline(1650, 8, 0.25),
        value: 1668.73,
        change: 7.89,
        changePercent: 0.47,
        week1: 3.45,
        ytd: 1.78,
        year1: 45.12,
        year3: 82.45,
    },
];

export const GLOBAL_MARKET_INDICES: MarketIndex[] = [
    {
        name: "S&P 500",
        flag: "🇺🇸",
        sparkline: generateSparkline(5900, 25, 0.5),
        value: 6025.99,
        change: 15.23,
        changePercent: 0.25,
        week1: 1.82,
        ytd: 4.15,
        year1: 22.34,
        year3: 45.67,
    },
    {
        name: "NASDAQ",
        flag: "🇺🇸",
        sparkline: generateSparkline(19500, 80, 1.2),
        value: 19843.77,
        change: 48.92,
        changePercent: 0.25,
        week1: 2.13,
        ytd: 5.67,
        year1: 28.45,
        year3: 52.89,
    },
    {
        name: "Dow Jones",
        flag: "🇺🇸",
        sparkline: generateSparkline(43500, 120, 0.8),
        value: 44546.08,
        change: -125.65,
        changePercent: -0.28,
        week1: 0.95,
        ytd: 3.24,
        year1: 18.76,
        year3: 38.45,
    },
    {
        name: "Nikkei 225",
        flag: "🇯🇵",
        sparkline: generateSparkline(39200, 150, -0.5),
        value: 39149.43,
        change: -234.12,
        changePercent: -0.59,
        week1: -1.23,
        ytd: 1.45,
        year1: 15.89,
        year3: 42.34,
    },
    {
        name: "Shanghai",
        flag: "🇨🇳",
        sparkline: generateSparkline(3350, 15, 0.2),
        value: 3368.07,
        change: 12.45,
        changePercent: 0.37,
        week1: 0.89,
        ytd: 2.34,
        year1: 8.56,
        year3: 12.78,
    },
    {
        name: "Hang Seng",
        flag: "🇭🇰",
        sparkline: generateSparkline(21800, 100, 0.6),
        value: 22195.68,
        change: 85.23,
        changePercent: 0.39,
        week1: 1.56,
        ytd: 3.78,
        year1: 12.45,
        year3: -5.67,
    },
    {
        name: "KOSPI",
        flag: "🇰🇷",
        sparkline: generateSparkline(2620, 12, -0.1),
        value: 2612.34,
        change: -8.45,
        changePercent: -0.32,
        week1: -0.67,
        ytd: 1.23,
        year1: 5.89,
        year3: 15.45,
    },
    {
        name: "FTSE 100",
        flag: "🇬🇧",
        sparkline: generateSparkline(8600, 30, 0.3),
        value: 8662.77,
        change: 22.34,
        changePercent: 0.26,
        week1: 1.12,
        ytd: 2.89,
        year1: 10.34,
        year3: 25.67,
    },
];

export const MACRO_INDICATORS: MacroIndicator[] = [
    // Lãi suất & Tiền tệ
    {
        name: "Lãi suất tái cấp vốn",
        category: "Lãi suất & Tiền tệ",
        value: "4.50",
        change: 0,
        changePercent: 0,
        unit: "%",
        period: "T1/2026",
        previousValue: "4.50",
        trend: "stable",
    },
    {
        name: "Lãi suất liên ngân hàng ON",
        category: "Lãi suất & Tiền tệ",
        value: "3.25",
        change: -0.15,
        changePercent: -4.41,
        unit: "%",
        period: "18/02/2026",
        previousValue: "3.40",
        trend: "down",
    },
    {
        name: "Tỷ giá USD/VND",
        category: "Lãi suất & Tiền tệ",
        value: "25,145",
        change: 35,
        changePercent: 0.14,
        unit: "VND",
        period: "18/02/2026",
        previousValue: "25,110",
        trend: "up",
    },
    {
        name: "Lãi suất tiết kiệm 12T",
        category: "Lãi suất & Tiền tệ",
        value: "5.20",
        change: 0.10,
        changePercent: 1.96,
        unit: "%",
        period: "T2/2026",
        previousValue: "5.10",
        trend: "up",
    },
    {
        name: "Tỷ giá EUR/VND",
        category: "Lãi suất & Tiền tệ",
        value: "27,320",
        change: -85,
        changePercent: -0.31,
        unit: "VND",
        period: "18/02/2026",
        previousValue: "27,405",
        trend: "down",
    },
    // Kinh tế vĩ mô
    {
        name: "GDP (YoY)",
        category: "Kinh tế vĩ mô",
        value: "6.80",
        change: 0.30,
        changePercent: 4.62,
        unit: "%",
        period: "Q4/2025",
        previousValue: "6.50",
        trend: "up",
    },
    {
        name: "CPI (YoY)",
        category: "Kinh tế vĩ mô",
        value: "3.45",
        change: 0.12,
        changePercent: 3.60,
        unit: "%",
        period: "T1/2026",
        previousValue: "3.33",
        trend: "up",
    },
    {
        name: "PMI Sản xuất",
        category: "Kinh tế vĩ mô",
        value: "51.20",
        change: 0.80,
        changePercent: 1.59,
        unit: "điểm",
        period: "T1/2026",
        previousValue: "50.40",
        trend: "up",
    },
    {
        name: "Sản xuất công nghiệp (YoY)",
        category: "Kinh tế vĩ mô",
        value: "8.50",
        change: 1.20,
        changePercent: 16.44,
        unit: "%",
        period: "T1/2026",
        previousValue: "7.30",
        trend: "up",
    },
    {
        name: "Bán lẻ hàng hóa (YoY)",
        category: "Kinh tế vĩ mô",
        value: "9.20",
        change: 0.50,
        changePercent: 5.75,
        unit: "%",
        period: "T1/2026",
        previousValue: "8.70",
        trend: "up",
    },
    // Thương mại & Đầu tư
    {
        name: "Xuất khẩu (YoY)",
        category: "Thương mại & Đầu tư",
        value: "14.50",
        change: 2.10,
        changePercent: 16.94,
        unit: "%",
        period: "T1/2026",
        previousValue: "12.40",
        trend: "up",
    },
    {
        name: "Nhập khẩu (YoY)",
        category: "Thương mại & Đầu tư",
        value: "12.80",
        change: 1.50,
        changePercent: 13.27,
        unit: "%",
        period: "T1/2026",
        previousValue: "11.30",
        trend: "up",
    },
    {
        name: "Cán cân thương mại",
        category: "Thương mại & Đầu tư",
        value: "1.85",
        change: 0.35,
        changePercent: 23.33,
        unit: "Tỷ USD",
        period: "T1/2026",
        previousValue: "1.50",
        trend: "up",
    },
    {
        name: "FDI đăng ký",
        category: "Thương mại & Đầu tư",
        value: "3.20",
        change: 0.45,
        changePercent: 16.36,
        unit: "Tỷ USD",
        period: "T1/2026",
        previousValue: "2.75",
        trend: "up",
    },
    {
        name: "FDI giải ngân",
        category: "Thương mại & Đầu tư",
        value: "1.90",
        change: 0.20,
        changePercent: 11.76,
        unit: "Tỷ USD",
        period: "T1/2026",
        previousValue: "1.70",
        trend: "up",
    },
    // Thị trường tài chính
    {
        name: "Dự trữ ngoại hối",
        category: "Thị trường tài chính",
        value: "105.00",
        change: 3.00,
        changePercent: 2.94,
        unit: "Tỷ USD",
        period: "Q4/2025",
        previousValue: "102.00",
        trend: "up",
    },
    {
        name: "Tín dụng tăng trưởng (YTD)",
        category: "Thị trường tài chính",
        value: "1.85",
        change: 1.85,
        changePercent: 100,
        unit: "%",
        period: "T1/2026",
        previousValue: "0.00",
        trend: "up",
    },
    {
        name: "M2 tăng trưởng (YoY)",
        category: "Thị trường tài chính",
        value: "12.50",
        change: 0.80,
        changePercent: 6.84,
        unit: "%",
        period: "T12/2025",
        previousValue: "11.70",
        trend: "up",
    },
    {
        name: "Nợ xấu ngân hàng",
        category: "Thị trường tài chính",
        value: "1.92",
        change: -0.08,
        changePercent: -4.00,
        unit: "%",
        period: "Q4/2025",
        previousValue: "2.00",
        trend: "down",
    },
    {
        name: "Giá vàng SJC",
        category: "Thị trường tài chính",
        value: "92.50",
        change: 1.50,
        changePercent: 1.65,
        unit: "Tr VND/lượng",
        period: "18/02/2026",
        previousValue: "91.00",
        trend: "up",
    },
];
